name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: yarn

      - name: yarn install
        run: yarn install
      - name: yarn test
        run: yarn test
      - name: yarn test:cache
        run: yarn test:cache
