name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: yarn run build
        run: yarn run build
      - name: yarn run lint:check
        run: yarn run lint:check
      - name: yarn run test
        run: yarn run test
