name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: yarn lint:check
        run: yarn lint:check
      - name: yarn test
        run: yarn test
      - name: yarn test:cypress:ci
        run: yarn test:cypress:ci
      - name: yarn build
        run: yarn build
