name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm
      - name: yarn install
        run: yarn install --prefer-offline
      - name: yarn run build
        run: yarn run build
      - name: yarn run lint:check
        run: yarn run lint:check
      - name: yarn run test
        run: yarn run test
      - name: yarn run test:cypress:ci
        run: yarn run test:cypress:ci
