name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install --frozen-lockfile
        run: yarn install --frozen-lockfile
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: node-v${{ matrix.node-version }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: yarn install
        run: yarn install
      - name: yarn run build
        run: yarn run build
      - name: yarn run lint:check
        run: yarn run lint:check
      - name: yarn run test
        run: yarn run test
      # https://docs.cypress.io/guides/continuous-integration/introduction#Caching
      # node_moddulesをキャッシュ対象にしてるので、サイプレスがサイプレスバイナリをダウンロードしない
      # - name: yarn run test:cypress:ci
      #   run: yarn run test:cypress:ci
